### ISSUE TITLE
ImageAnnotatorClient memory leak

### ISSUE THREAD

**Issue by nmeyvis** [googleapis/nodejs-vision#427] opened 2019-08-28 23:42 UTC
It's unclear from the [documentation](https://googleapis.dev/nodejs/vision/latest/v1p1beta1.ImageAnnotatorClient.html) how ImageAnnotatorClient should be used.

Consider two scenarios:
### Locally Scoped Client
```javascript
class GoogleVisionCategoryImageTester {

    constructor() {
    }

    async test(image) {
	let client = new vision.ImageAnnotatorClient();
        let imageBuffer = await image.buffer();

        let result = await client.safeSearchDetection(imageBuffer);
    }
}
```

### Instance Scoped Client
```javascript

class GoogleVisionCategoryImageTester {

    constructor() {
        this.client = new vision.ImageAnnotatorClient();
    }

    async test(image) {
        let imageBuffer = await image.buffer();

        let result = await this.client.safeSearchDetection(imageBuffer);
    }
}

```

#### Locally Scoped Client
Heap at start 20MB
Call test 20 times
Heap at end **38MB**

#### Instance Scoped Client
Heap at start 22MB
Call test 20 times
Heap at end **24MB**

I could not find any clean up methods like .close on the ImageAnnotatorClient so I assumed it would be properly handled by the garbage collector. Is the correct usage of ImageAnnotatorClient to maintain one instance? If so, I'd like to suggest adding that detail to the documentation and possibly adding a clean up method.

#### Environment details

  - OS: Windows 10 64bit (first noticed leak in unix)
  - Node.js version: v10.16.0
  - npm version: 6.9.0
  - `@google-cloud/vision` version: 1.1.1

**Comment by callmehiphop** [comment] 2019-09-03 22:22
@nmeyvis typically I would suggest keeping a single instance, otherwise each client you create will have to be authenticated.

@alexander-fenster @bcoe have either of you heard of/experienced issues with clients not being garbage collected?

**Comment by alexander-fenster** [comment] 2019-09-03 22:58
I agree with what @callmehiphop said - the suggested way to use the client is to keep a single client instance because creating a new client is a time consuming operation (it's actually asynchronous, even though the constructor returns immediately).

I tried doing the same - called methods of `ImageAnnotatorClient` several times and tracked memory usage. I didn't observe the pattern you mention. After the first request, the memory usage got up:

```
VSZ     RSS
936712  46604  # before the first request
1075616 48412  # after the first request
```

but then, with subsequent requests _using the same image_ (to make sure I'm not using extra memory for storing image bytes), I did not see any memory increases:

```
VSZ     RSS
1075616 48948  # subsequent requests
1075616 49012
1075616 48600
1075616 49128
1075616 49392
1075616 49180
1075616 49444
```

It makes me think that while some memory is allocated by gRPC (`@grpc/grpc-js`) and Node.js HTTP/2 stack, it does not increase memory usage when handling requests - in other words, it's unlikely that there is a substantial leak anywhere in gRPC request pipeline.

@nmeyvis Since you do see the memory increase in your instance scoped test, can I ask you to share the complete source code of your test as a gist, including the code that reads images from the filesystem (or web)? I'd like to see where the extra memory is coming from.

I checked with Node.js v8.15.0 (the oldest supported) on Linux.

**Comment by callmehiphop** [comment] 2019-09-09 19:17
@nmeyvis I'm going to close this issue since I don't think there's any actionable steps for us to take. Please let us know if you feel otherwise and we'll be happy to re-open!

**Closed by callmehiphop** 2019-09-09 19:17 UTC
Labels: type: question

**Comment by evilive3000** [comment] 2019-09-17 07:37
I use an instance scoped approach and got warning ` MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 16 close listeners added.`. Set higher limit of Listeners, but caught the same warning.

trace:
```
    at _addListener (events.js:254:17)
    at TLSSocket.addListener (events.js:270:10)
    at TLSSocket.Readable.on (_stream_readable.js:829:35)
    at Http2CallStream.attachHttp2Stream (/home/evilive/Projects/safesearch/node_modules/@grpc/grpc-js/build/src/call-stream.js:275:35)
    at Http2SubChannel.startCallStream (/home/evilive/Projects/safesearch/node_modules/@grpc/grpc-js/build/src/subchannel.js:110:20)
    at /home/evilive/Projects/safesearch/node_modules/@grpc/grpc-js/build/src/channel.js:205:28
    At processTicksAndRejections (internal/process/task_queues. j's: 89:5)
```

**Comment by callmehiphop** [comment] 2019-09-17 12:28
👋 @evilive3000 that sounds like a separate issue than the one being discussed here. Could I trouble you to open a new issue that includes a small reproduction case? Thanks!
