### ISSUE TITLE
ImageAnnotatorClient.batchAnnotateImages returns frequent "bad image data" requests.

### ISSUE THREAD

**Issue by simonmittag** [googleapis/nodejs-vision#168] opened 2018-08-10 08:52 UTC
- OS: MacOS, Linux
  - Node.js version: 10.8.0
  - npm version: 6.2.0
  - `@google-cloud/vision` version: 0.21.0

#### Steps to reproduce

  1. batch up multiple requests using ImageAnnotatorClient,batchAnnotateImages even just batches with 1 request.
  2. run against API with detection type 'documentTextDetection'
  3. repeat same file with ImageAnnotatorClient.documentTextDetection() without batch.
  4. count files with error codes using both approaches. Batch uploads produce higher numbers of error code "3" with "bad image data".

I have tested this from the same client computer and batchAnnotateImages fails on roughly 10% of my files, only to work the next time on the same file.

The client.documentTextDetection approach works reliably though.

**Comment by kinwa91** [comment] 2018-12-14 01:34
Hi @simonmittag, I was trying to reproduce the issue you described above, but I wasn't able to reproduce it.

In order to help us troubleshoot your issue, it'd be great if you could answer:

- Does it still happen with the latest version (0.23.0)?
- How many image files are you supplying to the batch request?
- Can you show us some code reproducing your issue?
- What is the format of the image (png, jpg..)?
- At what rate are you sending the requests? - you mentioned a 10% failure rate, how many requests is it out of?
- You mentioned "Batch uploads produce higher numbers of error code "3" with "bad image data"." and later you said "The client.documentTextDetection approach works reliably though.", does it mean that you cannot reproduce the error using the `documentTextDetection` method or is it reproducible, but at a lower rate?

Thanks!

**Comment by JustinBeckwith** [comment] 2019-02-08 17:36
Greetings!  We're going to go ahead and close this out for now.  If you can answer the questions above, we'd be happy to help!

**Closed by JustinBeckwith** 2019-02-08 17:36 UTC
Labels: :rotating_light:, needs more info, priority: p2, type: bug

**Comment by michaelfreund** [comment] 2019-02-20 08:48
Info might be helpful: Happens when you set `gzip: true` in bucketOptions for file upload.
